server:
  port: 8080

spring:
  application:
    name: user-service

  data:
    mongodb:
      host: host.docker.internal
      port: 27017
  kafka:
    bootstrap-servers: kafka:29092
    consumer:
      auto-offset-reset: earliest


eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka
