server:
  port: 8080

spring:
  application:
    name: user-service

  data:
    mongodb:
      host: host.docker.internal
      port: 27017
  kafka:
    bootstrap-servers: kafka:29092
    consumer:
      group-id: "spring-boot-avro-consumer-id"
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      autoOffsetReset: "earliest"
#spring.cloud.stream:
#  function:
#    definition: domainService
#  bindings:
#    domainService-in-0:
#      destination: active.web-domains
#  kafka:
#    bindings:
#      domainService-in-0:
#        consumer:
#          configuration:
#            value:
#              deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
#    binder:
#      brokers:
#        - localhost:9091
#        - localhost:9092

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka
