apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: kafka-cluster
spec:
  selector:
    app: api-gateway
  ports:
    - protocol: TCP
      port: 8765
      targetPort: 8765

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: kafka-cluster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: marymary88/mongo_gradle_study_project-api-gateway:latest
          ports:
            - containerPort: 8765