apiVersion: v1
kind: Service
metadata:
  labels:
    app: database-mongodb
  name: database-mongodb
  namespace: kafka-cluster
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: database-mongodb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: database-mongodb
  name: database-mongodb
  namespace: kafka-cluster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database-mongodb
  template:
    metadata:
      labels:
        app: database-mongodb
    spec:
      containers:
        - name: database-mongodb
          image: mongo:latest
          ports:
            - containerPort: 27017
              hostPort: 27017
          volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /data/db
      volumes:
        - name: mongo-persistent-storage
          hostPath:
            path: /data/storage/mongodb