apiVersion: v1
kind: Service
metadata:
  name: domain-crawler
  namespace: kafka-cluster
spec:
  selector:
    app: domain-crawler
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: domain-crawler
  namespace: kafka-cluster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: domain-crawler
  template:
    metadata:
      labels:
        app: domain-crawler
    spec:
      containers:
        - name: domain-crawler
          image: marymary88/mongo_gradle_study_project-domain-crawler:latest
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: kafka-service:29092
            - name: eureka-server
              value: eureka-server:8761