apiVersion: v1
kind: Service
metadata:
  name: proxy
  namespace: kafka-cluster
spec:
  selector:
    app: proxy
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy
  namespace: kafka-cluster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      labels:
        app: proxy
    spec:
      containers:
        - name: proxy
          image: marymary88/document_proxy:1.0.0
          ports:
            - containerPort: 8080
